environments:
  dev:
    values:
      - envValues/dev.yaml
    namespace: dev-namespace
  stage:
    values:
      - envValues/stage.yaml
    namespace: stage-namespace

releases:
  - name: hello-app
    namespace: "{{ .Namespace }}"
    chart: ./hello-chart
    version: 0.1.0
    values:
      - hello-chart/values.yaml
