environments:
  dev:
    values:
      - envValues/dev.yaml
      - secrets/dev-secrets.yaml

  stage:
    values:
      - envValues/stage.yaml
      - secrets/stage-secrets.yaml

releases:
  - name: hello-app-dev
    namespace: dev-namespace
    chart: ./hello-chart
    version: 0.1.5
    values:
      - hello-chart/values.yaml
      - envValues/dev.yaml
      - secrets/dev-secrets.yaml

  - name: hello-app-stage
    namespace: stage-namespace
    chart: ./hello-chart
    version: 0.1.5
    values:
      - hello-chart/values.yaml
      - envValues/stage.yaml
      - secrets/stage-secrets.yaml