environments:
  dev:
    values:
      - envValues/dev.yaml
      - secrets/dev-secrets.yaml

  stage:
    values:
      - envValues/stage.yaml
      - secrets/stage-secrets.yaml


releases:
  - name: hello-app
    namespace: "{{ .Values.namespace }}"
    chart: ./hello-chart
    version: 0.1.0
    values:
      - hello-chart/values.yaml
      - envValues/dev.yaml    # Explicitly specify for dev
      - envValues/stage.yaml  # Explicitly specify for stage
